### ISSUE TITLE
Google login button needs to be conformed to Google's design guidelines

### ISSUE THREAD

**Issue by restlessbit** [underdogio/underdog-styles#181]
See https://developers.google.com/identity/branding-guidelines

The button also needs to be updated in dogtag.

**Comment by restlessbit** [comment]
Unfortunately we would have to create our own assets in order to conform to these branding guidelines.

And if we wanted to use SVGs, we would also have to import the `Roboto` font just for the Google button, which would have an adverse impact on performance.

**Comment by cmuir** [comment]
@restlessbit Hmmm...I guess we'll be OK if we get the colors and icon correct.

**Comment by restlessbit** [comment]
Maybe we can use our existing `.btn--secondary` style, but flip the icon + text, and replace the icon with the one that the Goog's wants us to use.

<img width="247" alt="screen shot 2016-06-27 at 12 46 02 pm" src="https://cloud.githubusercontent.com/assets/6979137/16388017/427add36-3c65-11e6-94ad-e5fcdf8ee139.png">

**Comment by cmuir** [comment]
We'll probably get dinged for that by the Googs, if they ever see it (which is quite likely given that we're working with Yahoo already). We should be fine with using all of their styles _except_ for Roboto, like so:

![btn_google_signin_dark_normal_web](https://cloud.githubusercontent.com/assets/792109/16394920/8e807144-3c85-11e6-9496-6c9c5ed78fb2.png)

**Comment by restlessbit** [comment]
How much should this match with with our own button styling?

Here's what I got so far:

<img width="497" alt="screen shot 2016-07-11 at 12 16 49 pm" src="https://cloud.githubusercontent.com/assets/6979137/16737902/74dbcfb8-4761-11e6-8494-53534baf899b.png">

**Comment by cmuir** [comment]
That looks nice. Does it look crappy to all caps it like ours? Probably does...

**Comment by restlessbit** [comment]
I think it looks fine:

<img width="532" alt="screen shot 2016-07-11 at 12 23 19 pm" src="https://cloud.githubusercontent.com/assets/6979137/16738100/4c4d2122-4762-11e6-96f2-1dffb57a84b4.png">

**Comment by cmuir** [comment]
I dig!!
