### ISSUE TITLE
Header on "small" looks wonky

### ISSUE THREAD

**Issue by brettlangdon** [underdogio/underdog-styles#223]
The header for `underdog-styles` looks a little off on "small" device size.

![image](https://cloud.githubusercontent.com/assets/1320353/16923067/632c06cc-4ce6-11e6-8601-5655f84b1aba.png)

Obviously not an important issue, but wanted to document somewhere.

**Comment by restlessbit** [comment]
Gross.

**Comment by restlessbit** [comment]
PUP FTW
